//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 12:34:45 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/cfd/2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.gob.sat.cfd;
